#!/bin/sh

#
# Copyright 2011 Nicolas Thauvin. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE AUTHORS ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

if [ $# != 1 ]; then
    echo "usage: `basename $0` backup_dir"
    exit 1
fi

if [ $1 = "-h" ]; then
    echo "usage: `basename $0` backup_dir"
    exit 1
fi

BKPDIR=$1/`date +%Y%m%d_%H%M`
if [ ! -d $BKPDIR ]; then
    mkdir -p $BKPDIR
    if [ $? != 0 ]; then
	echo "Could not create $BKPDIR"
	exit 1
    fi
fi

echo "backup of /usr/pkg to $BKPDIR/usr_pkg.tgz"
cd /usr
tar cpzf $BKPDIR/usr_pkg.tgz pkg

cd /var/db
echo "backup of /var/db/pkg and /var/db/pkg.refcount to $BKPDIR/var_db_pkg.tgz"
tar cpzf $BKPDIR/var_db_pkg.tgz pkg pkg.refcount
echo "backup of /var/db/pkgin to $BKPDIR/var_db_pkgin.tgz"
tar cpzf $BKPDIR/var_db_pkgin.tgz pkgin
