#!/bin/sh

#
# Copyright 2011 Nicolas Thauvin. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE AUTHORS ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

usage() {
    echo "usage: `basename $0` [options] new_cvsroot dir [dir..]"
    echo "options:"
    echo "    -e regex        Exclude dirs matching regexp"
    echo "    -h              Print this help"
    exit $1
}

args=`getopt e:h $*`
if [ $? != 0 ]; then
    usage 1
fi

set -- $args
for o in $*; do
    case $o in
	-e) REGEX=$2; shift 2;;
	-h) usage 1;;
	--) shift; break;;
    esac
done

if [ $# -lt 2 ]; then
    usage 1
fi

URL=$1; shift

for dir in $*; do
    if [ -d "$dir" ]; then
	echo "==> $dir"
	find $dir -name 'Root' | grep 'CVS\/Root$' | while read file; do
	    if [ -n "$REGEX" ]; then
		# if path matches the exclusion regex, do not update cvs root
		echo $file | grep -E "$REGEX" > /dev/null 2>&1
		if [ $? = 0 ]; then
		    continue
		fi
	    fi

	    # replace the old url by the given one
	    echo $URL > $file
	done
    fi
done

